CREATE TABLE `Users`.`USUARIO` (
  `id` INT NOT NULL  AUTO_INCREMENT  COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `senha` VARCHAR(45) NULL COMMENT '',
  `sexo` VARCHAR(45) NULL COMMENT '',
  `candidato` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
AUTO_INCREMENT = 0;
